import type { Data, Vehicle, Service, Module } from "./index";
import { SCENARIO_REFERENCE_DATE } from "./scenario";

export function createSeed(referenceDate = SCENARIO_REFERENCE_DATE): Data {
  const all: Module[] = [
    "programari",
    "clienti",
    "vehicule",
    "itp",
    "intretinere",
    "tahografe",
    "locatii",
    "personal",
    "notificari",
    "rapoarte",
    "setari",
  ];
  const vehicles: Vehicle[] = [
    {
      id: "v1",
      customerId: "c1",
      locationId: "central",
      plate: "B 123 ABC",
      make: "Volkswagen",
      model: "Passat",
      year: 2021,
      mileage: 108450,
      category: "Autoturism",
      tires: "Anvelope de vară",
      tireDate: "2026-10-28",
    },
    {
      id: "v2",
      customerId: "c1",
      locationId: "nord",
      plate: "B 456 XYZ",
      make: "Dacia",
      model: "Duster",
      year: 2023,
      mileage: 42600,
      category: "Autoturism",
      tires: "Anvelope all season",
      tireDate: "2027-04-15",
    },
    {
      id: "v3",
      customerId: "c1",
      locationId: "industrial",
      plate: "B 789 VAN",
      make: "Mercedes-Benz",
      model: "Sprinter",
      year: 2020,
      mileage: 187200,
      category: "Autoutilitară",
      tires: "Anvelope all season",
      tireDate: "2027-03-10",
    },
    {
      id: "v4",
      customerId: "c1",
      locationId: "industrial",
      plate: "B 100 TRK",
      make: "MAN",
      model: "TGX",
      year: 2022,
      mileage: 312850,
      category: "Camion",
      tires: "Anvelope mixte",
      tireDate: "2027-02-20",
    },
    ...Array.from({ length: 10 }, (_, i): Vehicle => ({
      id: `f${i + 1}`,
      customerId: "c2",
      locationId: "industrial",
      plate: `IF ${210 + i} NTR`,
      make: ["MAN", "Volvo", "Mercedes-Benz", "DAF", "Renault"][i % 5],
      model: ["TGX", "FH 460", "Actros", "XF", "T High"][i % 5],
      year: 2020 + (i % 4),
      mileage: 180000 + i * 17250,
      category: "Camion",
      tires: "Anvelope mixte",
      tireDate: "2027-02-20",
    })),
    ...[
      ["c3", "B 234 MRC", "Toyota", "Corolla", "central"],
      ["c4", "B 567 DRA", "Škoda", "Octavia", "nord"],
      ["c5", "IF 88 ANA", "Ford", "Focus", "central"],
      ["c6", "B 920 RDU", "BMW", "320d", "nord"],
    ].map((a, i): Vehicle => ({
      id: `p${i}`,
      customerId: a[0],
      plate: a[1],
      make: a[2],
      model: a[3],
      locationId: a[4],
      year: 2019 + i,
      mileage: 64200 + i * 13200,
      category: "Autoturism",
      tires: "Anvelope de vară",
      tireDate: "2026-10-25",
    })),
  ];
  const seed: Data = {
    schemaVersion: 1,
    referenceDate: "2026-10-19",
    reminderDays: [30, 14, 7, 1],
    vehicles,
    customers: [
      [
        "c1",
        "Alex Ionescu",
        "alex.ionescu@example.com",
        "0721 456 890",
        "central",
      ],
      [
        "c2",
        "Nord Trans Logistic SRL",
        "flota@nordtrans.example",
        "0724 680 210",
        "industrial",
      ],
      [
        "c3",
        "Mihai Rădulescu",
        "mihai.radulescu@example.com",
        "0722 350 610",
        "central",
      ],
      [
        "c4",
        "Daria Marinescu",
        "daria.marinescu@example.com",
        "0723 901 450",
        "nord",
      ],
      [
        "c5",
        "Ana Dumitrescu",
        "ana.dumitrescu@example.com",
        "0725 210 630",
        "central",
      ],
      [
        "c6",
        "Radu Petrescu",
        "radu.petrescu@example.com",
        "0726 130 970",
        "nord",
      ],
    ].map((a) => ({
      id: a[0],
      name: a[1],
      email: a[2],
      phone: a[3],
      locationId: a[4],
      kind: a[0] === "c2" ? "Companie" : "Persoană fizică",
      preferences: {
        "Expirare ITP": true,
        Întreținere: true,
        Programări: true,
        "Noutăți și oferte": false,
      },
    })),
    locations: [
      {
        id: "central",
        name: "Locația Central",
        address: "Strada Atelierelor 24, București",
        phone: "031 555 01 10",
        services: [
          "ITP",
          "Mecanică",
          "Ulei și filtre",
          "Anvelope",
          "Alte servicii",
        ],
        opens: "08:00",
        closes: "18:00",
        capacity: 3,
        weekdays: [1, 2, 3, 4, 5, 6],
        breakStart: "12:00",
        breakEnd: "12:30",
      },
      {
        id: "nord",
        name: "Locația Nord",
        address: "Bulevardul Nordului 86, București",
        phone: "031 555 01 20",
        services: ["ITP", "Ulei și filtre", "Anvelope"],
        opens: "09:00",
        closes: "17:00",
        capacity: 2,
        weekdays: [1, 2, 3, 4, 5],
        breakStart: "12:30",
        breakEnd: "13:00",
      },
      {
        id: "industrial",
        name: "Locația Industrial",
        address: "Șoseaua Industriilor 142, București",
        phone: "031 555 01 30",
        services: ["ITP", "Mecanică", "Verificare tahograf", "Alte servicii"],
        opens: "07:00",
        closes: "19:00",
        capacity: 2,
        weekdays: [1, 2, 3, 4, 5],
        breakStart: "13:00",
        breakEnd: "13:30",
      },
    ],
    staff: [
      {
        id: "s0",
        name: "Cristian Pavel",
        email: "cristian.pavel@example.com",
        role: "Administrator principal",
        superAdmin: true,
        active: true,
        locationIds: ["central", "nord", "industrial"],
        permissions: all,
      },
      {
        id: "s1",
        name: "Andrei Popescu",
        email: "andrei.popescu@example.com",
        role: "Recepție",
        superAdmin: false,
        active: true,
        locationIds: ["central"],
        permissions: ["programari", "clienti", "vehicule", "notificari"],
      },
      {
        id: "s2",
        name: "Maria Ionescu",
        email: "maria.ionescu@example.com",
        role: "Operator ITP",
        superAdmin: false,
        active: true,
        locationIds: ["central", "nord"],
        permissions: ["programari", "clienti", "vehicule", "itp"],
      },
      {
        id: "s3",
        name: "Vlad Georgescu",
        email: "vlad.georgescu@example.com",
        role: "Tehnician tahografe",
        superAdmin: false,
        active: true,
        locationIds: ["industrial"],
        permissions: [
          "programari",
          "clienti",
          "vehicule",
          "tahografe",
          "intretinere",
        ],
      },
      {
        id: "s4",
        name: "Elena Stoica",
        email: "elena.stoica@example.com",
        role: "Consilier service",
        superAdmin: false,
        active: true,
        locationIds: ["nord"],
        permissions: [
          "programari",
          "clienti",
          "vehicule",
          "intretinere",
          "notificari",
        ],
      },
    ],
    appointments: [
      ...[
        ["p0", "ITP", "09:00", "Finalizată", "s1"],
        ["v1", "Ulei și filtre", "10:30", "Confirmată", "s1"],
        ["p2", "Anvelope", "11:00", "Înregistrată", "s2"],
        ["p0", "Mecanică", "14:00", "Confirmată", "s1"],
      ].map((a, i) => ({
        id: `a${i + 1}`,
        customerId: vehicles.find((v) => v.id === a[0])!.customerId,
        vehicleId: a[0],
        locationId: "central",
        service: a[1] as Service,
        date: "2026-10-19",
        time: a[2],
        duration: a[1] === "Mecanică" ? 60 : 30,
        status: a[3] as Data["appointments"][0]["status"],
        staffId: a[4],
        notes: "",
      })),
      ...[
        ["p1", "09:30", "În lucru"],
        ["v2", "11:30", "Confirmată"],
        ["p3", "15:00", "Înregistrată"],
      ].map((a, i) => ({
        id: `an${i}`,
        customerId: vehicles.find((v) => v.id === a[0])!.customerId,
        vehicleId: a[0],
        locationId: "nord",
        service: "ITP" as Service,
        date: "2026-10-19",
        time: a[1],
        duration: 30,
        status: a[2] as Data["appointments"][0]["status"],
        staffId: i === 0 ? "s2" : "s4",
        notes: "",
      })),
      ...["f1", "f3", "v4", "f5", "f7"].map((id, i) => ({
        id: `ai${i}`,
        customerId: vehicles.find((v) => v.id === id)!.customerId,
        vehicleId: id,
        locationId: "industrial",
        service: "Verificare tahograf" as Service,
        date: "2026-10-19",
        time: ["08:00", "09:00", "10:30", "14:00", "16:00"][i],
        duration: 60,
        status: "Confirmată" as const,
        staffId: "s3",
        notes: "",
      })),
      {
        id: "a-next",
        customerId: "c1",
        vehicleId: "v1",
        locationId: "central",
        service: "Anvelope",
        date: "2026-10-20",
        time: "10:30",
        duration: 30,
        status: "Confirmată",
        staffId: "s1",
        notes: "",
      },
      {
        id: "a-old",
        customerId: "c1",
        vehicleId: "v1",
        locationId: "central",
        service: "Ulei și filtre",
        date: "2026-01-12",
        time: "09:00",
        duration: 30,
        status: "Finalizată",
        staffId: "s1",
        notes: "",
      },
    ],
    itps: vehicles.map((v, i) => ({
      id: `itp-${v.id}`,
      vehicleId: v.id,
      expires:
        i === 0
          ? "2026-11-18"
          : i === 1
            ? "2027-06-12"
            : [
                "2026-10-25",
                "2026-10-29",
                "2026-10-16",
                "2026-11-02",
                "2027-02-15",
              ][i % 5],
      status:
        i % 4 === 0 ? "Programat" : i % 3 === 0 ? "Notificat" : "De contactat",
    })),
    rules: vehicles.flatMap((v, i) => [
      {
        id: `rule-${v.id}`,
        vehicleId: v.id,
        operation: "Ulei și filtre",
        intervalKm: i === 0 ? 10000 : 15000,
        intervalMonths: 12,
        lastKm: i === 0 ? 100000 : v.mileage - 13500 + i * 140,
        lastDate: i === 0 ? "2026-01-12" : "2025-11-05",
      },
      ...(i === 0
        ? [
            {
              id: "rule-belt",
              vehicleId: v.id,
              operation: "Distribuție",
              intervalKm: 120000,
              intervalMonths: 60,
              lastKm: 0,
              lastDate: "2021-11-10",
            },
          ]
        : []),
    ]),
    records: vehicles.map((v) => ({
      id: `record-${v.id}`,
      vehicleId: v.id,
      operation: "Ulei și filtre",
      date: "2026-01-12",
      mileage: v.id === "v1" ? 100000 : Math.max(0, v.mileage - 10000),
      locationId: v.locationId,
    })),
    tachographs: vehicles
      .filter((v) => v.category !== "Autoturism")
      .map((v, i) => ({
        id: `t-${v.id}`,
        vehicleId: v.id,
        type: i % 2 ? "Digital inteligent V2" : "Digital",
        serial: `DTCO-${824610 + i}`,
        lastDate: "2024-11-01",
        nextDate: ["2026-11-01", "2026-10-24", "2026-11-15", "2027-03-20"][
          i % 4
        ],
        locationId: "industrial",
        history: [
          { date: "2024-11-01", note: "Verificare periodică efectuată" },
        ],
      })),
    notifications: [
      {
        id: "n1",
        customerId: "c1",
        vehicleId: "v1",
        category: "ITP",
        title: "ITP-ul expiră în 30 de zile",
        body: "B 123 ABC · Valabil până la 18 noiembrie 2026. Alege din timp următoarea vizită.",
        date: "2026-10-19",
        status: "Trimisă",
        read: false,
      },
      {
        id: "n2",
        customerId: "c1",
        vehicleId: "v1",
        category: "Întreținere",
        title: "Mai ai 1.550 km până la schimbul de ulei",
        body: "Volkswagen Passat · Următorul prag: 110.000 km.",
        date: "2026-10-19",
        status: "Trimisă",
        read: false,
      },
      {
        id: "n3",
        customerId: "c1",
        vehicleId: "v1",
        appointmentId: "a-next",
        category: "Programări",
        title: "Programarea ta este mâine, la 10:30",
        body: "Anvelope · Locația Central. Te așteptăm!",
        date: "2026-10-19",
        status: "Trimisă",
        read: false,
      },
      {
        id: "n4",
        customerId: "c1",
        vehicleId: "v4",
        category: "Tahografe",
        title: "Verificarea tahografului se apropie",
        body: "MAN TGX · Termen: 24 octombrie 2026.",
        date: "2026-10-19",
        status: "Trimisă",
        read: true,
      },
      {
        id: "n5",
        customerId: "c2",
        vehicleId: "f1",
        category: "Tahografe",
        title: "Reamintire verificare tahograf",
        body: "IF 210 NTR · Verificare periodică.",
        date: "2026-10-20",
        status: "Programată",
        read: false,
      },
      {
        id: "n6",
        customerId: "c1",
        vehicleId: "v1",
        category: "Campanii",
        title: "Pregătește-ți mașina pentru sezonul rece",
        body: "Verifică starea anvelopelor înainte de următoarea călătorie.",
        date: "2026-10-18",
        status: "Trimisă",
        read: true,
      },
    ],
    activities: [
      {
        id: "act1",
        title: "Programare confirmată",
        detail: "Alex Ionescu · Anvelope",
        locationId: "central",
      },
      {
        id: "act2",
        title: "Verificare tahograf programată",
        detail: "Nord Trans Logistic · IF 210 NTR",
        locationId: "industrial",
      },
      {
        id: "act3",
        title: "Kilometraj actualizat",
        detail: "Dacia Duster · 42.600 km",
        locationId: "nord",
      },
      {
        id: "act4",
        title: "Client nou înregistrat",
        detail: "Ana Dumitrescu",
        locationId: "central",
      },
    ],
  };
  if (referenceDate === seed.referenceDate) return seed;
  const parsed = new Date(referenceDate + "T12:00:00Z");
  if (
    !/^\d{4}-\d{2}-\d{2}$/.test(referenceDate) ||
    isNaN(parsed.getTime()) ||
    parsed.toISOString().slice(0, 10) !== referenceDate
  )
    throw Error("Data de referință nu este validă.");
  const shift =
    parsed.getTime() - Date.parse(seed.referenceDate + "T12:00:00Z");
  const shifted: Data = JSON.parse(JSON.stringify(seed), (_key, value) =>
    typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)
      ? new Date(Date.parse(value + "T12:00:00Z") + shift)
          .toISOString()
          .slice(0, 10)
      : value,
  );
  shifted.notifications[0].body = `B 123 ABC · Valabil până la ${shifted.itps[0].expires}. Alege din timp următoarea vizită.`;
  shifted.notifications[3].body = `MAN TGX · Termen: ${shifted.tachographs.find((t) => t.vehicleId === "v4")?.nextDate}.`;
  return shifted;
}
